/*TMODJS:{"version":"1.0.0"}*/
!function(){function a(a,b){return(/string|function/.test(typeof b)?h:g)(a,b)}function b(a,c){return"string"!=typeof a&&(c=typeof a,"number"===c?a+="":a="function"===c?b(a.call(a)):""),a}function c(a){return l[a]}function d(a){return b(a).replace(/&(?![\w#]+;)|[<>"']/g,c)}function e(a,b){if(m(a))for(var c=0,d=a.length;d>c;c++)b.call(a,a[c],c,a);else for(c in a)b.call(a,a[c],c)}function f(a,b){var c=/(\/)[^/]+\1\.\.\1/,d=("./"+a).replace(/[^/]+$/,""),e=d+b;for(e=e.replace(/\/\.\//g,"/");e.match(c);)e=e.replace(c,"/");return e}function g(b,c){var d=a.get(b)||i({filename:b,name:"Render Error",message:"Template not found"});return c?d(c):d}function h(a,b){if("string"==typeof b){var c=b;b=function(){return new k(c)}}var d=j[a]=function(c){try{return new b(c,a)+""}catch(d){return i(d)()}};return d.prototype=b.prototype=n,d.toString=function(){return b+""},d}function i(a){var b="{Template Error}",c=a.stack||"";if(c)c=c.split("\n").slice(0,2).join("\n");else for(var d in a)c+="<"+d+">\n"+a[d]+"\n\n";return function(){return"object"==typeof console&&console.error(b+"\n\n"+c),b}}var j=a.cache={},k=this.String,l={"<":"&#60;",">":"&#62;",'"':"&#34;","'":"&#39;","&":"&#38;"},m=Array.isArray||function(a){return"[object Array]"==={}.toString.call(a)},n=a.utils={$helpers:{},$include:function(a,b,c){return a=f(c,a),g(a,b)},$string:b,$escape:d,$each:e},o=a.helpers=n.$helpers;a.get=function(a){return j[a.replace(/^\.\//,"")]},a.helper=function(a,b){o[a]=b},"function"==typeof define?define(function(){return a}):"undefined"!=typeof exports?module.exports=a:this.template=a,/*v:1*/
a("index",function(a,b){"use strict";var c=this,d=(c.$helpers,function(d,f){f=f||a;var g=c.$include(d,f,b);return e+=g}),e="";return e+="  ",d("./partial/header"),e+='  <section class="section">  <div class="container auth-container"></div> </section>  ',d("./partial/footer"),new k(e)}),/*v:1*/
a("partial/activity",""),/*v:1*/
a("partial/footer",'<footer class="footer"> <div class="wrapper"> <nav class="footer-nav"> <ul> <li> <a href="agreement.html">\u7528\u6237\u534f\u8bae</a> </li> <li> <a href="joinus.html">\u8054\u7cfb\u6211\u4eec</a> </li> <li> <a href="about.html">\u5173\u4e8e\u6211\u4eec</a> </li> <li> <a href="statement.html">\u514d\u8d23\u58f0\u660e</a> </li> </ul> </nav> <nav class="footer-state"> <ul> <li>@2013 \u6821\u6821 All rights reserved \u6caaICP\u590713039888\u53f7</li> <li>|</li> <li>Designed by M.Y.studio</li> </ul> </nav> </div> </footer>'),/*v:1*/
a("partial/header",'<header class="header web-header"> <div class="wrapper header-wrapper clearfix"> <div class="pull-left logo-wrapper"> <a href="javascript:void(0);"> <img src="../images/logo.png" /></a> </div> <div class="pull-right nav-wrapper clearfix"> <ul class="nav header-nav pull-left"> <li> <a href="index.html"> <span>\u9996\u9875</span> </a> </li> <li> <a href="about.html"> <span>\u5173\u4e8e\u6211\u4eec</span> </a> </li> <li> <a href="joinus.html"> <span>\u52a0\u5165\u6211\u4eec</span> </a> </li> <li> <a href="download.html" class="current"> <span>App\u4e0b\u8f7d</span> </a> </li> </ul> <div class="login-wrapper pull-left" id="userBox"> <span id="BTN_LOGIN" data-xx-login-action="loginBox">\u767b\u9646</span> <i></i> <span id="BTN_SIGNUP" data-xx-login-action="signupBox">\u6ce8\u518c</span> </div> </div> </div> </header>'),/*v:1*/
a("partial/hotArticles",""),/*v:1*/
a("partial/login",""),/*v:1*/
a("partial/organization",""),/*v:1*/
a("partial/signup","")}();